@startuml
class ApplicationUser {
    + ApplicationUser()
    + ApplicationUser(id:string, name:string, surname:string, userName:string)
    + Name : string? <<get>> <<set>>
    + Surname : string? <<get>> <<set>>
}
IdentityUser <|-- ApplicationUser
@enduml
